import fs from 'fs/promises';
import path from 'path';
import sharp from 'sharp';
import type { UploadedFile } from 'express-fileupload';
import type { IConfig } from '../../interfaces/config.js';
import type { User } from '../../models/user.js';

export const AVATAR_SIZE = 256;

export const avatarDirectory = (config: IConfig): string => config.assets.userAvatarLocation || '/etc/oblecto/assets/userAvatars/';

// Stored avatar names are generated by saveAvatar; basename() keeps a bad row from pointing outside the directory.
export const avatarPath = (config: IConfig, avatar: string): string => path.join(avatarDirectory(config), path.basename(avatar));

export async function removeAvatarFile(config: IConfig, avatar: string | null): Promise<void> {
    if (!avatar) return;

    await fs.rm(avatarPath(config, avatar), { force: true });
}

export class AvatarError extends Error {
    // Picked up by the REST error handler
    constructor(message: string, public statusCode: number) {
        super(message);
        this.name = 'AvatarError';
    }
}

// The first file of a multipart upload, whatever its field name.
export function firstUpload(files: unknown): UploadedFile | undefined {
    const first = Object.values((files ?? {}) as Record<string, UploadedFile | UploadedFile[]>)[0];

    return Array.isArray(first) ? first[0] : first;
}

/**
 * Crop the upload to a square WebP, make it the user's avatar and drop the old
 * one. Every upload gets a new name so URLs carrying it can be cached forever.
 */
export async function saveAvatar(config: IConfig, user: User, upload: UploadedFile | undefined): Promise<void> {
    if (!upload) throw new AvatarError('Image file is missing', 400);

    const avatar = `${user.id}-${Date.now()}.webp`;

    await fs.mkdir(avatarDirectory(config), { recursive: true });

    try {
        await sharp(upload.tempFilePath || upload.data)
            .rotate()
            .resize(AVATAR_SIZE, AVATAR_SIZE, { fit: 'cover' })
            .webp()
            .toFile(avatarPath(config, avatar));
    } catch {
        throw new AvatarError('File is not an image', 422);
    } finally {
        if (upload.tempFilePath) await fs.rm(upload.tempFilePath, { force: true });
    }

    const previous = user.avatar;

    user.avatar = avatar;
    await user.save();
    await removeAvatarFile(config, previous);
}

export async function clearAvatar(config: IConfig, user: User): Promise<void> {
    const previous = user.avatar;

    user.avatar = null;
    await user.save();
    await removeAvatarFile(config, previous);
}
