import fs from 'fs/promises';
import path from 'path';
import type { IConfig } from '../../interfaces/config.js';

export const AVATAR_SIZE = 256;

export const avatarDirectory = (config: IConfig): string => config.assets.userAvatarLocation || '/etc/oblecto/assets/userAvatars/';

// Stored avatar names are generated by the upload route; basename() keeps a bad row from pointing outside the directory.
export const avatarPath = (config: IConfig, avatar: string): string => path.join(avatarDirectory(config), path.basename(avatar));

export async function removeAvatarFile(config: IConfig, avatar: string | null): Promise<void> {
    if (!avatar) return;

    await fs.rm(avatarPath(config, avatar), { force: true });
}
