name: Mocha Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libavahi-compat-libdnssd-dev python3-guessit

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm ci
    - run: npm run test:mocha
